# Panorama logs (fluentbit) for K8s - ClusterRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-log-reader
rules:
- apiGroups: [""]
  resources:
    - namespaces
    - pods
    - nodes
    - nodes/proxy
  verbs:
    - get
    - list
    - watch

---
# Panorama logs (fluentbit) for K8s - ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-log-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-log-reader
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: kube-system

---
# Panorama logs (fluentbit) for K8s - DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit-test
  namespace: kube-system
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      serviceAccountName: fluent-bit
      containers:
      - name: aws-for-fluent-bit
        env:
          - name: FLB_LOG_LEVEL
            value: debug
        image: docker.io/aulasneo/panorama-elt-logs:0.1.8b
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: mnt
          mountPath: /mnt
          readOnly: true
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 100Mi
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: mnt
        hostPath:
          path: /mnt

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
  labels:
    app.kubernetes.io/name: fluentbit
data:
  fluent-bit.conf: |
        [SERVICE]
            Parsers_File  parsers.conf
        [INPUT]
            Name              tail
            Tag               kube.*
            Path              /var/log/containers/lms*.log
            Exclude_Path      /var/log/containers/lms-worker*.log
            Parser            docker
            DB                /var/log/flb_kube.db
            Mem_Buf_Limit     256MB
            DB.locking        true
            Rotate_Wait       30
            Skip_Long_Lines   Off
            Refresh_Interval  10
        [FILTER]
            Name             kubernetes
            Match            kube.*
            Kube_URL         https://kubernetes.default.svc:443
            Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
            Kube_Tag_Prefix  kube.var.log.containers.
            Merge_Log        On
            Merge_Log_Key    log_processed
            Use_Kubelet      true
            Kubelet_Port     10250
            Buffer_Size      0
        [OUTPUT]
            Name             s3
            Match            *
            bucket           panoramabuckets10f2cc5a-rawlogsca996da2-17rgtucyg6g4g
            region           us-east-1
            compression      gzip
            use_put_object   On
            total_file_size  1M
            upload_timeout   3m
  parsers.conf: |
        [PARSER]
            Name             docker
            Format           json
            Time_Key         time
            Time_Format      %Y-%m-%dT%H:%M:%S.%L
            Time_Keep        On
        [PARSER]
            Name              event
            Format            regex
            Regex             ^[^\{]+(?<event>\{.*\})$
        [PARSER]
            Name              tracking-parser
            Format            regex
            Regex             ^(?<timestamp>[^ ] [^ ]) (?<level>.+) \d+ \[(?<logtype>.+)\] \[user (?<user>\d+)\] \[ip (?<ip>[0-9\.]+)\] (?<process>[^ ]+) - (?<eventlog>.*)$
            Time_Key          timestamp
            Time_Format       %Y-%m-%d %H:%M:%S,%L


